version: "3.7"

services:
  db:
    container_name: wordlift-multisite_db
    image: mysql:5.7
    volumes:
      - db-data-5.5-multisite:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  wordpress:
    container_name: wordlift-multisite_wordpress
    image: wordpress:5.5
    depends_on:
      - db
    volumes:
      - wordpress-data-5.5-multisite:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/wordlift
    environment:
      WL_DISABLE_SPARQL_UPDATE_QUERIES_BUFFERING: "true"
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        # Add support for the reverse proxy.
        if ( strpos( $$_SERVER['HTTP_X_FORWARDED_PROTO'], 'https' ) !== false ) {
        	$$_SERVER['HTTPS'] = 'on';
        }

        if ( isset( $$_SERVER['HTTP_X_FORWARDED_HOST'] ) ) {
          $$_SERVER['HTTP_HOST'] = $$_SERVER['HTTP_X_FORWARDED_HOST'];
        }

        # Define the site and home URLs.
        # define( 'WP_SITEURL', 'https://wordlift.localhost' );
        # define( 'WP_HOME', WP_SITEURL );

        # Allow all entity types.
        define( 'WL_ALL_ENTITY_TYPES', true );

        # Enable Debug logging to the /wp-content/debug.log file
        define( 'WP_DEBUG_LOG', true );
        # Disable display of errors and warnings
        define( 'WP_DEBUG_DISPLAY', false );
        @ini_set( 'display_errors', 0 );
        # Use dev versions of core JS and CSS files (only needed if you are modifying these core files)
        define( 'SCRIPT_DEBUG', true );

        # Enable WordLift debug.
        define( 'WL_DEBUG', WP_DEBUG );
        define( 'WL_LOG_LEVEL', 0 );

        /* Multisite */
        define('WP_ALLOW_MULTISITE', true );
    entrypoint: /var/www/html/wp-content/plugins/wordlift/.docker-custom-entrypoint.sh

  nginx:
    container_name: wordlift-multisite_nginx
    image: nginx:1.17
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d
    environment:
      NGINX_HOST: wordpress
      NGINX_SERVER_NAME: wordlift.localhost
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_SERVER_NAME' < /etc/nginx/conf.d/wordpress.template > /etc/nginx/conf.d/wordpress.conf && nginx -g 'daemon off;'"

  cli:
    container_name: wordlift-multisite_cli
    image: wordpress:cli-2.2
    depends_on:
      - db
    user: xfs
    volumes:
      - wordpress-data-5.5-multisite:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/wordlift
    tty: true

volumes:
  db-data-5.5-multisite:
  wordpress-data-5.5-multisite:
